language: cpp
compiler:
  - clang
  - gcc
env:
  - CMAKE_PARAMS="-DCMAKE_BUILD_TYPE=Release -DUSE_EXCEPTIONS=1 -DUNITY_BUILD=ON"
  - CMAKE_PARAMS="-DCMAKE_BUILD_TYPE=Release -DUNITY_BUILD=OFF"
  - CMAKE_PARAMS="-DCMAKE_BUILD_TYPE=Debug -DUSE_EXCEPTIONS=1"
dist: trusty
sudo: false
script: cmake -G"Unix Makefiles" $CMAKE_PARAMS && make && reset && Demos/UnitTests/UnitTests -au
