#pragma once

#include "Decorators/Take.h"
#include "Decorators/TakeUntil.h"
#include "Decorators/TakeUntilAny.h"
#include "Decorators/Filter.h"
#include "Decorators/Map.h"
#include "Decorators/Stride.h"
#include "Decorators/Transversal.h"
#include "Decorators/Retro.h"
#include "Decorators/Cycle.h"
#include "Decorators/Split.h"
#include "Decorators/Join.h"
#include "Decorators/Chunks.h"
#include "Decorators/ByLine.h"
