#pragma once

#define INTRA_DETAIL_SKIP_FIRST_ARG(firstArg, ...) __VA_ARGS__
#define INTRA_SKIP_FIRST_ARG(x, ...) INTRA_DETAIL_SKIP_FIRST_ARG x

#define INTRA_DETAIL_SELECT_FIRST_ARG(firstArg, ...) firstArg
#define INTRA_DETAIL_SELECT_FIRST_ARG_CONVERT(args) INTRA_DETAIL_SELECT_FIRST_ARG args
#define INTRA_SELECT_FIRST_ARG(x) INTRA_DETAIL_SELECT_FIRST_ARG_CONVERT( (x) )

#define INTRA_DETAIL_CONCATENATE_TOKENS(x, y) x ## y
#define INTRA_CONCATENATE_TOKENS(x, y) INTRA_DETAIL_CONCATENATE_TOKENS(x, y)
#define INTRA_MACRO_ARGUMENT(...) __VA_ARGS__
#define INTRA_MACRO_EXPAND(x) x

